server:
  port: 8085
  
spring:
  cloud:
    gateway:
      routes:
      #Route Mapping
      - id: Product-Service               #RouteIdentifiler
        uri: http://localhost:8789/       #Respective microservice URL which needs to be  
        predicates:
        - Path= /api/product/**
        
      - id: Cart-Service               #RouteIdentifiler
        uri: http://localhost:8790/       #Respective microservice URL which needs to be  
        predicates:
        - Path= /api/cart/**
         
      - id: Order-Service               #RouteIdentifiler
        uri: http://localhost:8791/       #Respective microservice URL which needs to be  
        predicates:
        - Path= /api/order/** 
        
      - id: Profile-Service               #RouteIdentifiler
        uri: http://localhost:8888/       #Respective microservice URL which needs to be  
        predicates:
        - Path= /api/auth/** 
        
        
        